spring.application.name=kenstar_crm
server.servlet.context-path=/kenstar_crm
server.port=8086

###############
# POSTGRES
###############
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.platform=postgres
#spring.datasource.name=postgres
#spring.datasource.driverClassName=org.postgresql.Driver 
spring.datasource.url=jdbc:postgresql://localhost:5432/kenstar_crm
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


spring.security.user.name=admin
spring.security.user.password=12345
