spring.application.name=kenstar_crm
server.servlet.context-path=/kenstar_crm
server.address=172.22.22.218
server.port=8087

###############
# POSTGRES
###############
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.platform=postgres
#spring.datasource.name=postgres
#spring.datasource.driverClassName=org.postgresql.Driver 
spring.datasource.url=jdbc:postgresql://localhost:5432/kenstar_crm
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE



spring.security.user.name=admin
spring.security.user.password=12345



springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#springdoc.api-docs.path=/api-docs
# Swagger related properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/v1/api-docs
#/swagger-ui.html

# working url for swagger :  http://172.22.22.218:8087/kenstar_crm/v1/swagger-ui/index.html


# Path matching strategy
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
